# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request]

jobs:
  buildlinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Check Linting
        run: yarn lint:check
      - name: Check Coding Style
        run: yarn style:check
      - name: Test with Coverage
        run: |
          # Check coverage, if coverage is below 100% for any files exit & print a message
          yarn test --experimental-test-coverage > test-output.txt

          cat test-output.txt

          grep "tests/compiled/src" test-output.txt | awk -F'|' '
            BEGIN {
              status=0;
            }
            {
              for (i=2; i<NF; i++) {
                if ($i+0 < 100) {
                  status=1;
                  printf "%s has less than 100%% coverage in all criterias\n", $1;
                  exit status;
                }
              }
            }
            END {
              exit status;
            }'
